backend:
  name: git-gateway
  branch: main
   # Branch to update (optional; defaults to master)
   # as in github master changed to main so main
# These lines should *not* be indented
media_folder: "public/assets/blog" # Media files will be stored in the repo under static/images/uploads
public_folder: "/assets/blog" 
# as in media folder we mentioned the root folder so we dont have to write that again
# The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "blog"
    label: "Blog"
    folder: "src/blog" # the actual path from where they are coming
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
            # name that is present in frontmatter
            # label that is present in ui
      - { label: "Title" , name: "title", widget: "string" }
      - { label: "Description" , name: "description", widget: "string" }
      - { label: "Author" , name: "author", widget: "string" }
      - { label: "Date" , name: "date", widget: "datetime" }
      - { label: "Tags" , name: "tags", widget: "list", default: ["post"] }
      - { label: "Featured Image" , name: "image", widget: "image" }
      - { label: "Image caption" , name: "imageAlt", widget: "string" }
      - { label: "Body", name: "body" , widget: "markdown" }